server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template-location: true
    cache: false
#  security:
#    user:
#      name: testUser
#      password: qwer1234
