server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template-location: true
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      username: sa
      password:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql


#  security:
#    user:
#      name: testUser
#      password: qwer1234
